
'use strict';
function sortedReadings(){return[...patient().readings].sort((a,b)=>stamp(b)-stamp(a))}
function resetForms(){medForm.reset();medId.value='';readingForm.reset();readingId.value='';const n=localNow();readingDate.value=n.date;readingTime.value=n.time}
function renderProfiles(){patientSwitch.innerHTML=Object.entries(state.patients).map(([k,p])=>`<button class="patient-button ${k===state.activePatient?'active':''}" data-p="${k}">${esc(p.name)}</button>`).join('');document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{state.activePatient=b.dataset.p;save();resetForms();renderAll()})}
function renderPatient(){patientName.value=patient().name;patientNote.value=patient().note||''}
function renderMeds(){medRows.innerHTML=patient().medications.length?patient().medications.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.dose)}</td><td>${esc(m.times)}</td><td>${esc(m.notes)}</td><td class="no-print"><button class="small" data-me="${m.id}">Editar</button> <button class="small danger" data-md="${m.id}">Eliminar</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No hay medicamentos registrados.</td></tr>';document.querySelectorAll('[data-me]').forEach(b=>b.onclick=()=>editMed(b.dataset.me));document.querySelectorAll('[data-md]').forEach(b=>b.onclick=()=>deleteMed(b.dataset.md))}
function renderReadings(){const a=sortedReadings();readingRows.innerHTML=a.length?a.map(r=>`<tr><td>${fmtDate(r.date)}</td><td>${esc(r.time)}</td><td><strong>${r.sys}</strong></td><td><strong>${r.dia}</strong></td><td>${r.pulse}</td><td>${esc(r.medRelation)}</td><td>${esc(r.notes)}</td><td class="no-print"><button class="small" data-re="${r.id}">Editar</button> <button class="small danger" data-rd="${r.id}">Eliminar</button></td></tr>`).join(''):'<tr><td colspan="8" class="empty">Todavía no hay mediciones.</td></tr>';document.querySelectorAll('[data-re]').forEach(b=>b.onclick=()=>editReading(b.dataset.re));document.querySelectorAll('[data-rd]').forEach(b=>b.onclick=()=>deleteReading(b.dataset.rd))}
function renderStats(){const a=filteredReadings(),last=a[a.length-1];periodLabel.textContent=a.length?`${fmtDate(a[0].date)} a ${fmtDate(last.date)}`:'Sin registros en el período';const min=(k)=>a.length?Math.min(...a.map(x=>+x[k])):'—',max=(k)=>a.length?Math.max(...a.map(x=>+x[k])):'—';stats.innerHTML=[['Total almacenado',patient().readings.length],['En el período',a.length],['Promedio sistólica',avg(a,'sys')],['Promedio diastólica',avg(a,'dia')],['Promedio pulso',avg(a,'pulse')],['Última toma',last?`${last.sys}/${last.dia}`:'—']].map(([k,v])=>`<div class="stat"><span class="muted">${k}</span><b>${v}</b></div>`).join('');drawChart(a)}
function renderAll(){renderProfiles();renderPatient();renderMeds();renderReadings();renderStats()}
patientName.onchange=e=>{patient().name=e.target.value.trim()||'Paciente';save('Nombre actualizado');renderProfiles()};patientNote.onchange=e=>{patient().note=e.target.value.trim();save('Observación actualizada')};
medForm.onsubmit=e=>{e.preventDefault();const o={id:medId.value||uid('med'),name:medName.value.trim(),dose:medDose.value.trim(),times:medTimes.value.trim(),notes:medNotes.value.trim()},i=patient().medications.findIndex(x=>x.id===o.id);i>=0?patient().medications[i]=o:patient().medications.push(o);log(i>=0?'editar_medicamento':'agregar_medicamento',o.name);save('Medicamento guardado');resetForms();renderAll()};
function editMed(x){const m=patient().medications.find(v=>v.id===x);if(!m)return;medId.value=m.id;medName.value=m.name;medDose.value=m.dose;medTimes.value=m.times;medNotes.value=m.notes;medName.focus()}
function deleteMed(x){const m=patient().medications.find(v=>v.id===x);if(m&&confirm(`¿Eliminar ${m.name}?`)){patient().medications=patient().medications.filter(v=>v.id!==x);save('Medicamento eliminado');renderMeds()}}
cancelMed.onclick=resetForms;
readingForm.onsubmit=e=>{e.preventDefault();const o={id:readingId.value||uid('read'),date:readingDate.value,time:readingTime.value,sys:+sys.value,dia:+dia.value,pulse:+pulse.value,medRelation:medRelation.value,notes:readingNotes.value.trim()};if(o.sys<=o.dia)return alert('La sistólica debe ser mayor que la diastólica.');const a=patient().readings,i=a.findIndex(x=>x.id===o.id);i>=0?a[i]=o:a.push(o);a.sort((x,y)=>stamp(x)-stamp(y));let removed=false;if(a.length>MAX_READINGS){a.shift();removed=true}log(i>=0?'editar_medicion':'agregar_medicion',`${o.date} ${o.sys}/${o.dia}`);save(removed?'Medición guardada; se eliminó la más antigua.':'Medición guardada');resetForms();renderAll()};
function editReading(x){const r=patient().readings.find(v=>v.id===x);if(!r)return;readingId.value=r.id;readingDate.value=r.date;readingTime.value=r.time;sys.value=r.sys;dia.value=r.dia;pulse.value=r.pulse;medRelation.value=r.medRelation||'';readingNotes.value=r.notes||'';readingDate.focus();scrollTo({top:readingForm.getBoundingClientRect().top+scrollY-20,behavior:'smooth'})}
function deleteReading(x){const r=patient().readings.find(v=>v.id===x);if(r&&confirm(`¿Eliminar la medición del ${fmtDate(r.date)}?`)){patient().readings=patient().readings.filter(v=>v.id!==x);save('Medición eliminada');renderAll()}}
cancelReading.onclick=resetForms;rangeSelect.onchange=renderStats;addEventListener('resize',()=>drawChart(filteredReadings()));
backupBtn.onclick=()=>{save();download(`CardioRegistro_V3_respaldo_${localNow().date}.json`,JSON.stringify(state,null,2),'application/json');toast('Respaldo descargado')};
restoreBtn.onclick=()=>restoreFile.click();restoreFile.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=migrate(JSON.parse(await f.text()));if(confirm('¿Reemplazar los datos actuales por este respaldo?')){state=x;save('Respaldo recuperado');resetForms();renderAll()}}catch(err){alert('No se pudo recuperar: '+err.message)}finally{e.target.value=''}};
diagnosticBtn.onclick=()=>{log('informe_tecnico');save();download(`CardioRegistro_V3_informe_tecnico_${localNow().date}.txt`,['CardioRegistro V3.0.3 — Informe técnico',`Fecha: ${new Date().toLocaleString('es-AR')}`,`Navegador: ${navigator.userAgent}`,`Paciente: ${patient().name}`,`Mediciones: ${patient().readings.length}`,`Medicamentos: ${patient().medications.length}`,'','Historial:',...state.diagnostics.map(x=>`${x.at} | ${x.action} | ${x.detail}`),'','Descripción del inconveniente:','................................................................'].join('\n'));toast('Informe técnico descargado')};
printBtn.onclick=()=>{log('imprimir_pdf',patient().name);save('La sesión fue guardada. Se abrirá la impresión/PDF.');setTimeout(()=>print(),350)};
resetForms();renderAll();log('inicio','CardioRegistro V3.0.3');save();setTimeout(()=>{const n=Object.values(state.patients).reduce((s,p)=>s+p.readings.length,0);if(n)toast(`CardioRegistro V3.0.3 listo: ${n} mediciones cargadas en total.`)},450);
